name: Auto Tag and Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Get latest tag and bump patch version
        id: tag
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest"
          version=$(echo "$latest" | sed 's/^v//' | awk -F. '{ printf("v%d.%d.%d", $1, $2, $3 + 1) }')
          echo "New version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create new tag and push
        run: |
          git tag ${{ steps.tag.outputs.version }}
          git push origin ${{ steps.tag.outputs.version }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          name: Release ${{ steps.tag.outputs.version }}
          generate_release_notes: true
